apiVersion: v1
kind: Namespace
metadata:
  name: mcp-store
---
apiVersion: v1
kind: Secret
metadata:
  name: mcp-secrets
  namespace: mcp-store
type: Opaque
stringData:
  GEMINI_API_KEY: YOUR_API_KEY
